# Generated by Django 5.0.6 on 2024-05-27 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anouncements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('numberoflots', models.IntegerField()),
                ('typeofprocurement', models.CharField(max_length=255)),
                ('procurementmethod', models.CharField(max_length=255)),
                ('tenderowner', models.CharField(max_length=255)),
                ('tendertitle', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('opendate', models.DateField()),
                ('opentime', models.CharField(choices=[('09:00', '09:00'), ('10:00', '10:00'), ('14:00', '14:00'), ('15:00', '15:00')], max_length=50)),
                ('anouncementpublicfile', models.CharField(max_length=255)),
                ('anouncementprivatefile', models.CharField(max_length=255)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=255)),
                ('alpha2', models.CharField(max_length=2)),
                ('alpha3', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Migrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migration', models.CharField(max_length=255)),
                ('batch', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsCenters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnouncementReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('anouncement', models.ManyToManyField(to='tender.anouncements')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now_add=True)),
                ('anouncement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tender.anouncements')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsesecuritysubmite', models.CharField(max_length=50)),
                ('discount', models.FloatField()),
                ('discountdol', models.FloatField()),
                ('discounteuro', models.FloatField()),
                ('total', models.FloatField()),
                ('totaldol', models.FloatField()),
                ('totaluro', models.FloatField()),
                ('vat', models.FloatField()),
                ('vatdol', models.FloatField()),
                ('vateuro', models.FloatField()),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('anouncement', models.ManyToManyField(to='tender.anouncements')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=50)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ManyToManyField(to='tender.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Lots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotnumber', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('discount', models.FloatField()),
                ('discountdol', models.FloatField()),
                ('discounteuro', models.FloatField()),
                ('total', models.FloatField()),
                ('totaldol', models.FloatField()),
                ('totaleuro', models.FloatField()),
                ('vat', models.FloatField()),
                ('vatdol', models.FloatField()),
                ('vateuro', models.FloatField()),
                ('responsesecuritysubmited', models.CharField(max_length=255)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tender.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentfile', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now_add=True)),
                ('anouncement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.anouncements')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projectscenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.projectscenters')),
            ],
        ),
        migrations.CreateModel(
            name='AnouncerFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('project', models.ManyToManyField(to='tender.projects')),
            ],
        ),
        migrations.AddField(
            model_name='anouncements',
            name='projectid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.projects'),
        ),
        migrations.AddField(
            model_name='anouncements',
            name='projectcenteranouncement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.projectscenters'),
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('middlename', models.CharField(max_length=255)),
                ('companyname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('division', models.CharField(max_length=255)),
                ('postalcode', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=100)),
                ('addressline1', models.CharField(max_length=255)),
                ('addressline2', models.CharField(max_length=255)),
                ('addressline3', models.CharField(max_length=255)),
                ('remembertoken', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companyountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.countries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
